name: stuffy_paradise
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  state_notifier:
  injectable:
  get_it:
  animated_custom_dropdown: ^3.1.1
  flutter_state_notifier:
  sqflite_common_ffi: ^2.3.4
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  injectable_generator:

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
