name: Web workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.1'
      - name: Build Windows
        run: flutter build windows
      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/x64/runner/Release/stuffy_paradise.exe

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: "MyApp Release v1.0.0"
          body: "First release of MyApp."
          draft: false
          prerelease: false

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/x64/runner/Release/stuffy_paradise.exe
          asset_name: stuffy_paradise.exe
          asset_content_type: application/octet-stream